// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RuntimeRepository is an autogenerated mock type for the RuntimeRepository type
type RuntimeRepository struct {
	mock.Mock
}

// ExistsRuntimeByIDAndAuthID provides a mock function with given fields: ctx, tenantID, id, authID
func (_m *RuntimeRepository) ExistsRuntimeByIDAndAuthID(ctx context.Context, tenantID string, id string, authID string) (bool, error) {
	ret := _m.Called(ctx, tenantID, id, authID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) bool); ok {
		r0 = rf(ctx, tenantID, id, authID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, tenantID, id, authID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
